# Generated by Django 4.2.11 on 2024-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosDePessoasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo_anterior', models.CharField(choices=[('NS', 'Não Sabe'), ('EF', 'Extra Firme'), ('F', 'Firme'), ('I', 'Intermediário'), ('M', 'Macio')], max_length=2)),
                ('idade', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('peso', models.FloatField()),
                ('tem_doenca', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True)),
            ],
        ),
    ]
