# Generated by Django 4.2.11 on 2024-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
