# Generated by Django 4.2.11 on 2024-09-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recomendar', '0003_alter_dadosdepessoasmodel_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDeColchoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel_de_maciez', models.IntegerField()),
                ('categoria', models.CharField(choices=[('EF', 'Extra Firme'), ('F', 'Firme'), ('I', 'Intermediário'), ('M', 'Macio')], max_length=60)),
            ],
        ),
    ]
